### ISSUE TITLE
[ENHANCEMENT] Add Bruno for API endpoints 

### ISSUE THREAD

**Issue by AkisKourouklis** [vanguardvirtual/repo-ranger#11]
**Is your feature request related to a problem? Please describe. (optional)**
We don not have right now a good API Documentation solution. I am using postman on localhost but postman is not free and opensource.

**Describe the solution you'd like (required)**
Add Bruno to the project and create a folder called bruno and save all the endpoints in their. Now we are using postman but we want to migrate to a better free and open source solution.

**Additional context (optional)**
- [Bruno](https://www.usebruno.com)

**Comment by AkisKourouklis** [comment]
Updated README.md with all the dependencies and credits
- Created CONTRIBUTING.md with the code of conduct and the process for submitting pull requests
- Created .env.example files

Commit [5bb7d111e2531c03886677d2a6944cc882d39b91](https://github.com/vanguardvirtual/repo-ranger/commit/5bb7d111e2531c03886677d2a6944cc882d39b91)

**Comment by vr-varad** [comment]
Hey @AkisKourouklis as my last pr is merged, I would like to contribute to this issue if its open for contribution.

**Comment by AkisKourouklis** [comment]
@vr-varad Hello Bruno, thanks a lot for contributing to repo-ranger, this will help our launch on product launch on Sept 29 to be even better. Yes you can contribute to this issue i am not currently working on it.

I am also posting here the Postman Collection (2.1) I exported , it will help you finish it even faster. 

[repo-ranger-postman-export.json](https://github.com/user-attachments/files/17045584/repo-ranger-postman-export.json)

**Comment by vr-varad** [comment]
Thanks

**Comment by vr-varad** [comment]
hey @AkisKourouklis in env.example u have mentioned using mongodburl and in db MySQL has been used?

**Comment by vr-varad** [comment]
i am almost done but unable to test.

**Comment by AkisKourouklis** [comment]
@vr-varad yes we are using both MySQL and Mongodb. I am using mongodb just for the agenda for cron jobs. If you setup a local mongodb instance you can test it.

I did a lot of changes and pushed a lot in the past few days. If you can't test it just push them and I will review and do the testing
Thanks a lot

**Comment by AkisKourouklis** [comment]
Changes here: https://github.com/vanguardvirtual/repo-ranger/commit/c34ebca1af96717875d20af4321f158e6c336f85
