### ISSUE TITLE
[ENHANCEMENT] Number formating on score

### ISSUE THREAD

**Issue by AkisKourouklis** [vanguardvirtual/repo-ranger#18]
**Is your feature request related to a problem? Please describe. (optional)**
If a user has a very large score for example 100K it now shows as 100000 we need to add formating and for example show it as 100,000

If not leave blank.

**Describe the solution you'd like (required)**
Just create a react util on the frontend that formats numbers.

**Comment by vr-varad** [comment]
Hey @AkisKourouklis I could work on this.

**Comment by AkisKourouklis** [comment]
@vr-varad Yes you could, we just need to have formatting on score numbers on the front. You could create a util that does that.
