### ISSUE TITLE
[ENHANCEMENT] Unit Tests API

### ISSUE THREAD

**Issue by AkisKourouklis** [vanguardvirtual/repo-ranger#5]
Create unit test with over 90% for the API.

- Use Jest and setup eslint to workwith it as well.
- Run tests with husky, on pre-commit

**Comment by vr-varad** [comment]
@AkisKourouklis I would like to work for this issue if its open for contribution

**Comment by AkisKourouklis** [comment]
Hello Varad, yes it is open you can work on it. Open a pull request when you are done. 

I need to create a code of conduct and contribution .md files as well. So it is clear to everyone how they can contribute.

For the mean time ask any questions you might have here.

**Comment by vr-varad** [comment]
Thanks I will start working on it.
