### ISSUE TITLE
[ENHANCEMENT] Typescript API Refactor Types and Interfaces

### ISSUE THREAD

**Issue by AkisKourouklis** [vanguardvirtual/repo-ranger#6]
In the API now we have types and interfaces inside `types.ts` we need to refactor that and move each type to it's own file.

- controller.types.ts
- database.types.ts
etc

Preferably create a folder types/ and move all the type files in their.

**Comment by vr-varad** [comment]
@AkisKourouklis Will be working on these!!

**Comment by AkisKourouklis** [comment]
@vr-varad great ! 👌

**Comment by vr-varad** [comment]
hey @AkisKourouklis Sorry but I am not exactly getting what is wanted here, Can u explain in brief??

**Comment by AkisKourouklis** [comment]
@vr-varad This ticket should be closed it is done. For some reason it was never closed.
