### ISSUE TITLE
[ENHANCEMENT] Create 404 Page

### ISSUE THREAD

**Issue by AkisKourouklis** [vanguardvirtual/repo-ranger#9]
Create 404 page for the frontend. Now error shows up with error boundaries.

We need a simple design just a 404 on the middle of the page and a link below. Go back to homepage.

![Image](https://github.com/user-attachments/assets/a94797ef-e6b9-40f0-a440-0f1ede428b5a)

**Comment by vr-varad** [comment]
Hey @AkisKourouklis Thanks for the last PR, I would like to work on this?

**Comment by AkisKourouklis** [comment]
@vr-varad Yes you can work on it. Just a simple 404 it is nothing special with a single button link.
